<h1>Cadastro de produtos</h1>

<form action="/Index/cadastrar" method="post">
	<div class="form-group">
		<label for="nome">Nome:</label>
		<input type="text" id="nome" name="nome" class="form-control">
	</div>
	<div class="form-group">
		<label for="preco">Preço:</label>
		<input type="text" id="preco" name="preco" class="form-control">
	</div>
	<div class="form-group">
		<label for="descricao">Descrição:</label>
		<textarea name="descricao" id="descricao" class="form-control"></textarea>
	</div>
	<div class="form-group">
		<input type="submit" value="Cadastrar" class="btn btn-primary">
	</div>
</form>