<?php 
	$form->prepare();
	$form->setAttribute('action',$this->url('application',['action' => 'cadastrar']));
 ?>
<h1>Cadastro de produtos</h1>

<?php 
	echo $this->form()->openTag($form);
 ?>
	<div class="form-group">
		<label for="nome">Nome:</label>
		<?php 
			echo $this->formInput($form->get('nome'));

            echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
        	->render($form->get('nome'));
        ?>
	</div>
	<div class="form-group">
		<label for="preco">Preço:</label>
		<?php 
			echo $this->formInput($form->get('preco'));
		?>
	</div>
	<div class="form-group">
		<label for="descricao">Descrição:</label>
		<?php 
			echo $this->formTextarea($form->get('descricao'));
		?>
	</div>
	<div class="form-group">
		<input type="submit" value="Cadastrar" class="btn btn-primary">
	</div>
<?php 
	echo $this->form()->closeTag();
 ?>