<h1>Editar produto</h1>

<form action="/Index/editar" method="post">
	<input type="hidden" name="id" value="<?= $produto->getId(); ?>">
	<div class="form-group">
		<label for="nome">Nome:</label>
		<input type="text" id="nome" name="nome" class="form-control" value="<?= $produto->getNome(); ?>">
	</div>
	<div class="form-group">
		<label for="preco">Preço:</label>
		<input type="text" id="preco" name="preco" class="form-control" value="<?= $produto->getPreco(); ?>">
	</div>
	<div class="form-group">
		<label for="descricao">Descrição:</label>
		<textarea name="descricao" id="descricao" class="form-control"><?= $produto->getDescricao(); ?></textarea>
	</div>
	<div class="form-group">
		<input type="submit" value="Cadastrar" class="btn btn-primary">
	</div>
</form>