<table class="table">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Preço</th>
			<th>Descrição</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach($produtos as $prod) {
				
		 ?>
		 	<tr>
				<td><?= $prod->getNome();?></td>
				<td><?= $prod->getPreco();?></td>
				<td><?= $prod->getDescricao();?></td>
				<td><a href="<?= $this->url('application',array('action' => 'deletar','id'=> $prod->getId()));?>" class="btn btn-danger">Remover</a>
				<a href="<?= $this->url('application',array('action' => 'editar','id'=> $prod->getId()));?>" class="btn btn-info">Editar</a></td>
			</tr>
		<?php 
			}
		 ?>
	</tbody>
</table>

<?php 
	$paging = $this->paginationHelper($produtos, $page, '/Produtos', 1); 
	echo $paging;
?>