<h1>Login !</h1>
<form action="<?= $this->url('application',['controller' => 'Usuario','action' => 'logar']); ?>" method="post">
	<div class="form-group">
		<label for="">Email</label>
		<input type="text" name="email" class="form-control" />
	</div>
	<div class="form-group">
		<label for="">Senha</label>
		<input type="password" name="senha" class="form-control" />
	</div>

	<div class="form-group">
		<input type="submit" value="Entrar" class="btn btn-primary"/>
	</div>
</form>